10.4 email test
braginsm/dualboot-python-course pull request #28
Opened 2023-06-15 07:51 UTC by braginsm

2023-06-16 06:07 UTC, kirill-gorshkov requested changes

2023-06-16 06:07 UTC, kirill-gorshkov commented on task_manager/settings.py
> +            BASE_DIR / "task_manager/templates",
Лучше сделать BASE_DIR / "task_manager" / "templates"

2023-06-16 06:07 UTC, kirill-gorshkov commented on test/test_send_email.py
> +        task = Task.objects.create(
Таск необходимо создавать через action_client

2023-06-16 06:55 UTC, kirill-gorshkov requested changes

2023-06-16 06:55 UTC, kirill-gorshkov commented on test/test_send_email.py
> +        task = self.create(
Уже лучше, но в задаче:
```
assignee = self.action_client.create_user()
task = self.action_client.create_task(assignee_id=assignee.id)
```

2023-06-16 07:10 UTC, braginsm commented on test/test_send_email.py
> +        task = self.create(
т.е. эти экшны нужно в `TestViewSetBase` реализовать?

2023-06-16 07:22 UTC, kirill-gorshkov commented on test/test_send_email.py
> +        task = self.create(
В прошлых уроках это рассказывалось: [action client](https://learn.dualboot.ru/courses/12/lessons/156/practices/2269)

2023-06-23 07:28 UTC, braginsm commented on test/test_send_email.py
> +        task = self.create(
done

2023-06-23 10:03 UTC, kirill-gorshkov approved these changes

2023-06-23 10:11 UTC, merged