11.4 tests
braginsm/dualboot-python-course pull request #33
Opened 2023-06-21 05:59 UTC by braginsm

2023-06-22 06:19 UTC, aleksandr-semenov-dbp requested changes

2023-06-22 06:19 UTC, aleksandr-semenov-dbp commented on test/test_task.py
> +        result["state"] = str(task.state)
```
result = {
    **task.__dict__,
    "author": task.author.id,
    ....
}
```
индексация типа a["bb"] = cc некрасивая, стремимся писать более декларативно

2023-06-23 07:29 UTC, braginsm commented on test/test_task.py
> +        result["state"] = str(task.state)
зарефачил метод

2023-06-23 08:15 UTC, aleksandr-semenov-dbp approved these changes

2023-06-23 09:46 UTC, merged