5.2 models implementation
braginsm/dualboot-python-course pull request #7
Opened 2023-06-05 09:23 UTC by braginsm

2023-06-05 15:54 UTC, aleksandr-semenov-dbp requested changes

2023-06-05 15:54 UTC, aleksandr-semenov-dbp commented on task_manager/main/models/task.py
> +    date_update = models.DateTimeField(auto_now_add=True, blank=True)
auto_now_add?

2023-06-05 15:54 UTC, aleksandr-semenov-dbp commented on task_manager/main/models/task.py
> +class Task(models.Model):
Надо добавить хотя бы автора и/или исполнителя, а также теги

2023-06-06 06:48 UTC, braginsm commented on task_manager/main/models/task.py
> +    date_update = models.DateTimeField(auto_now_add=True, blank=True)
поправил

2023-06-06 06:49 UTC, braginsm commented on task_manager/main/models/task.py
> +class Task(models.Model):
готово

2023-06-06 08:16 UTC, kirill-gorshkov requested changes

2023-06-06 08:16 UTC, kirill-gorshkov commented on task_manager/main/models/task.py
> +    date_update = models.DateTimeField(auto_now_add=True, blank=True)
Не вижу исправлений

2023-06-06 08:54 UTC, merged