5.4 admin
braginsm/dualboot-python-course pull request #8
Opened 2023-06-05 14:07 UTC by braginsm

2023-06-05 15:59 UTC, aleksandr-semenov-dbp requested changes
В задании было "Модели некрасиво отображаются — Tag object (1) и у модели User нет поля role" надо с этим разобраться

2023-06-06 08:18 UTC, kirill-gorshkov requested changes

2023-06-06 08:18 UTC, kirill-gorshkov commented on task_manager/main/models/user.py
> +    )
А теперь пользователь будет отображаться как User(1) :(

2023-06-06 08:30 UTC, kgorshkoff approved these changes

2023-06-06 08:54 UTC, merged